backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    fields:
      - { name: "title", label: "Skill Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { name: "title", label: "Project Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "tech", label: "Technologies", widget: "list" }
      - { name: "demo", label: "Demo URL", widget: "string", required: false }
      - { name: "source", label: "Source Code URL", widget: "string", required: false }
